### ISSUE TITLE
[Bug]: Copy paste not working

### ISSUE THREAD

**Issue by Chengym2023** [Comfy-Org/ComfyUI_frontend#2561]
### Frontend Version

 ComfyUI 0.3.14
ComfyUI_frontend v1.8.13

### Expected Behavior

<html>
<body>

Ctrl + C/Ctrl + V | Copy and paste selected nodes (without maintaining connections to outputs of unselected nodes)
-- | --
Ctrl + C/Ctrl + Shift + V | Copy and paste selected nodes (maintaining connections from outputs of unselected nodes to inputs of pasted nodes)

</body>
</html>
edge,chrome cannot copy nodes,but firebox work fine?

### Actual Behavior

-

### Steps to Reproduce

-

### Debug Logs

```powershell
-
```

### Browser Logs

-

### Setting JSON

-

### Other

-

┆Issue is synchronized with this [Notion page](https://www.notion.so/Issue-2561-Bug-Copy-paste-not-working-19b6d73d3650814bbc06c046ea6c7022) by [Unito](https://www.unito.io)

**Comment by LukeG89** [comment]
It's working for me, both on Edge and Chrome. Yesterday another user on Discord had a similar issue on Edge, maybe there is a conflict with a custom node or something?

**Comment by Chengym2023** [comment]
> It's working for me, both on Edge and Chrome. Yesterday another user on Discord had a similar issue on Edge, maybe there is a conflict with a custom node or something?
edge automatic upgrade caused this bug, and then i try update edge to new version.it working.so fuck edge.

**Comment by lycos2019** [comment]
> > It's working for me, both on Edge and Chrome. Yesterday another user on Discord had a similar issue on Edge, maybe there is a conflict with a custom node or something?
> > edge automatic upgrade caused this bug, and then i try update edge to new version.it working.so fuck edge.

Have you find a solution ?

**Comment by Chengym2023** [comment]
> > > It's working for me, both on Edge and Chrome. Yesterday another user on Discord had a similar issue on Edge, maybe there is a conflict with a custom node or something?
> > > edge automatic upgrade caused this bug, and then i try update edge to new version.it working.so fuck edge.
> 
> Have you find a solution ?

update edge

**Comment by lycos2019** [comment]
latest ver 133.0.3065.69. copy paste still doesn't work

> > > > It's working for me, both on Edge and Chrome. Yesterday another user on Discord had a similar issue on Edge, maybe there is a conflict with a custom node or something?
> > > > edge automatic upgrade caused this bug, and then i try update edge to new version.it working.so fuck edge.
> > 
> > 
> > Have you find a solution ?
> 
> update edge

latest ver 133.0.3065.69. copy paste still doesn't work

**Comment by Chengym2023** [comment]
> latest ver 133.0.3065.69. copy paste still doesn't work
> 
> > > > > It's working for me, both on Edge and Chrome. Yesterday another user on Discord had a similar issue on Edge, maybe there is a conflict with a custom node or something?
> > > > > edge automatic upgrade caused this bug, and then i try update edge to new version.it working.so fuck edge.
> > > 
> > > 
> > > Have you find a solution ?
> > 
> > 
> > update edge
> 
> latest ver 133.0.3065.69. copy paste still doesn't work

try update comfyui from manager

**Comment by lycos2019** [comment]
> > latest ver 133.0.3065.69. copy paste still doesn't work
> > > > > > It's working for me, both on Edge and Chrome. Yesterday another user on Discord had a similar issue on Edge, maybe there is a conflict with a custom node or something?
> > > > > > edge automatic upgrade caused this bug, and then i try update edge to new version.it working.so fuck edge.
> > > > 
> > > > 
> > > > Have you find a solution ?
> > > 
> > > 
> > > update edge
> > 
> > 
> > latest ver 133.0.3065.69. copy paste still doesn't work
> 
> try update comfyui from manager

![Image](https://github.com/user-attachments/assets/d726c63c-84c9-4779-9d51-0cccec82d0f3)

already did.  since its not working I installed chrome. then it worked for a couple of hours and now its not working. Everything is uptodate.  I can't even copy but it only pastes one node. its like the copy storage is full. anything out side of comfyui webui can be copied and pasted. btw i'm using portable version.

**Comment by Shyryp** [comment]
The problem started to appear a couple of days ago on all updated Chrome browsers (I assume this was a major update to the Chromium engine, which Edge is also based on) on all computers, although I did not update ComfyUI or its nodes.

However, on the current latest version of ComfyUI Frontend there is no such problem, with one exception - in other languages ​​of the system CTRL+C, CTRL+Z, CTRL+V do not work (or work incorrectly). It is necessary to add multilingualism in "Keybinding" for default hotkeys and multiple hotkeys for one action.

**Comment by WasitSam37** [comment]
I encountered the same problem this morning on my 'Microsoft Edge Chromium' after updating ComfyUI using the 'Update All' option in the 'ComfyUI Manager.'

After the update, it seems to be remembering the last node I copied before the update. As a result, every time I press Ctrl+V, it only pastes that previously copied node, and I can't copy any new nodes.

I attempted to clear my browser cookies and tested it in a new workflow, and now the Ctrl+C, Ctrl+V, and Ctrl+Shift+V shortcuts are completely broken for nodes. I can’t use any of them.

The only functionality that works is copying an image from any source and pasting it into the workflow.

***

If I remember correctly, my 'Edge Chromium' just received a new update recently. However, everything was still working fine until I updated ComfyUI this morning.

***

As a workaround, I just installed a fresh version of Firefox, and it works perfectly.

***

EDITED: updated for 'Edge Chromium'

I don't know why, but when I [ HOLD 'Ctrl' + HOLD 'C' ] for a few seconds instead of [ HOLD 'Ctrl' + PRESS 'C' ], I can now copy and paste the node as it should be.

However, it still doesn't work when I just [ PRESS 'Ctrl' + 'C' ]

**Comment by LukeG89** [comment]
> I encountered the same problem this morning on my 'Microsoft Edge Chromium' after updating ComfyUI using the 'Update All' option in the 'ComfyUI Manager.'

@WasitSam37 Check if you are in a Stable ComfyUI or Nightly ComfyUI, because this issue has been fixed with [this commit](https://github.com/comfyanonymous/ComfyUI/pull/6814) 5 days ago, but the latest Stable release of ComfyUI [v0.3.14](https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.3.14) is from 2 weeks ago.  

![Image](https://github.com/user-attachments/assets/424221da-e539-4812-aaaf-5146a95c5371)

**Comment by WasitSam37** [comment]
> [@WasitSam37](https://github.com/WasitSam37) Check if you are in a Stable ComfyUI or Nightly ComfyUI, because this issue has been fixed with [this commit](https://github.com/comfyanonymous/ComfyUI/pull/6814) 5 days ago, but the latest Stable release of ComfyUI [v0.3.14](https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.3.14) is from 2 weeks ago.

Thank you very much! I just switched from Stable to Nightly. 
The 'ComfyUI frontend' has been updated to v1.9.18, and now it works perfectly!

![Image](https://github.com/user-attachments/assets/ef7ae7ec-4563-447d-a808-0ab65f74008b)

**Comment by MrYutz** [comment]
I have the same issue.  Ctrl + V doesn't work.  I can only paste a single node that I copied last week.

Bug is present in Chrome, but not in a clean install of Firefox.

In Chrome:
Long pressing Ctrl + C does work around the issue.  It actually seems to replace the cache, and that "new" set of nodes is the only thing that will paste until another long press Ctrl + C.


Solution:
**Update ComfyUI to latest.  Issue resolved.**


Just adding notes for anyone else that might search for this.

**Comment by g0ro** [comment]
Updating the frontend to the latest version (1.13.8) did not help, Ctrl+C still doesn't work in latest Firefox
But Ctrl+Insert works great instead of Ctrl+C

**Comment by LukeG89** [comment]
> Updating the frontend to the latest version (1.13.8) did not help, Ctrl+C still doesn't work in latest Firefox

@g0ro I cannot reproduce the issue with v1.13.8 on latest Firefox (version 136.0.2), I just tested it with all nodes disabled and copy-pasting is working correctly (in my case it also works with all nodes enabled, maybe you have a node that is conflicting)

Can you reproduce the issue with `--disable-all-custom-nodes` argument?
Also, do you have any browser extensions that can cause the issue?

**Comment by g0ro** [comment]
@LukeG89 , after updating everything, it works flawlessly, tested both Firefox and Chrome (win10).
I'm running ComfyUI inside SwarmUI, it might had been a cause.

Anyway, if Ctrl+C doesn't work, try Ctrl+Ins

**Comment by Jatts-Art** [comment]
Not sure if my issue is exactly the same, but I cannot Ctrl+C to copy either.... _unless_ I press the caps lock key, and then it works. I am also on Edge browser.

**Comment by DarkAlchy** [comment]
I am on 0.3.34 and cannot ctrl-c/v nodes.  a royal pain that I was hoping this version fixed as I lost this ability with 0.3.28.

ComfyUI version: 0.3.34
ComfyUI frontend version: 1.18.10

Well, I went digging and saw this has happened to Chrome, and Chromium based browser and your ComfyUI before, so I fired up Firefox and sure enough it worked, and worked fast too.
